service: backend-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: app.handler
    environment:
      WATSON_WORKSPACE_USERNAME: NEED TO IMPLEMENT ENCRYPTING THIS AT REST IN GIT
      WATSON_WORKSPACE_PASSWORD: NEED TO IMPLEMENT ENCRYPTING THIS AT REST IN GIT
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
